# claim.py – Send claim() transaction on Base Mainnet
# Reads claim_data.json generated by sign.py
from web3 import Web3
from eth_account import Account
import json
import sys

# ── CONFIG ──────────────────────────────────────────────────────────────
RPC_URL       = "https://mainnet.base.org"
USER_PRIVKEY  = "0xYOUR_WALLET_PRIVATE_KEY"   # private key of 0xfEc5...d1b8
CONTRACT_ADDR = "0xFc54307bc86a93Fa1a0aA7DD32c75dc9498c1E8D"
CHAIN_ID      = 8453
# ────────────────────────────────────────────────────────────────────────

ABI_CLAIM = [
    {
        "inputs": [
            {"internalType": "string",  "name": "tick",        "type": "string"},
            {"internalType": "uint256", "name": "totalAmount", "type": "uint256"},
            {"internalType": "uint256", "name": "nonce",       "type": "uint256"},
            {"internalType": "bytes",   "name": "signature",   "type": "bytes"}
        ],
        "name": "claim",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }
]

# ── Load claim data ──────────────────────────────────────────────────────
try:
    with open("claim_data.json", "r") as f:
        data = json.load(f)
except FileNotFoundError:
    print("ERROR: claim_data.json not found – run sign.py first.")
    sys.exit(1)

tick         = data["tick"]
total_amount = int(data["totalAmount"])
nonce        = int(data["nonce"])
signature    = bytes.fromhex(data["signature"].replace("0x", ""))

# ── Connect ──────────────────────────────────────────────────────────────
w3 = Web3(Web3.HTTPProvider(RPC_URL))

if not w3.is_connected():
    print("ERROR: Cannot connect to RPC. Check your internet connection.")
    sys.exit(1)

account  = Account.from_key(USER_PRIVKEY)
contract = w3.eth.contract(
    address=Web3.to_checksum_address(CONTRACT_ADDR),
    abi=ABI_CLAIM
)

print("=" * 60)
print(f"  Wallet          : {account.address}")
print(f"  Tick            : {tick}")
print(f"  Amount          : {total_amount / 10**18:.4f} {tick}")
print(f"  Nonce           : {nonce}")
print(f"  Signature       : 0x{signature.hex()[:24]}...")
print(f"  Contract        : {CONTRACT_ADDR}")
print(f"  Chain ID        : {CHAIN_ID}")
print("=" * 60)

# ── Gas estimation (pre-flight check) ───────────────────────────────────
print("\n  Estimating gas...")
try:
    estimated_gas = contract.functions.claim(
        tick, total_amount, nonce, signature
    ).estimate_gas({"from": account.address})
    print(f"  Estimated gas   : {estimated_gas}")
except Exception as e:
    print(f"\n  ERROR: Gas estimation failed – transaction would revert.")
    print(f"  Reason: {e}")
    print("\n  Possible causes:")
    print("    - Signature is invalid (wrong signer key used)")
    print("    - Nonce mismatch (check nonces[] via check.py)")
    print("    - Nothing to claim (already claimed or wrong totalAmount)")
    sys.exit(1)

# ── Build transaction ────────────────────────────────────────────────────
base_fee      = w3.eth.gas_price
max_fee       = int(base_fee * 1.5)
priority_fee  = w3.to_wei("0.05", "gwei")

tx = contract.functions.claim(
    tick,
    total_amount,
    nonce,
    signature
).build_transaction({
    "from":                 account.address,
    "nonce":                w3.eth.get_transaction_count(account.address),
    "gas":                  estimated_gas + 20000,
    "maxFeePerGas":         max_fee,
    "maxPriorityFeePerGas": priority_fee,
    "chainId":              CHAIN_ID
})

# ── Sign and send ────────────────────────────────────────────────────────
print("\n  Signing and sending transaction...")
signed_tx = account.sign_transaction(tx)
tx_hash   = w3.eth.send_raw_transaction(signed_tx.raw_transaction)
tx_hex    = tx_hash.hex()

print(f"\n  TX sent     : 0x{tx_hex}")
print(f"  BaseScan    : https://basescan.org/tx/0x{tx_hex}")
print("\n  Waiting for confirmation (up to 120s)...")

# ── Wait for receipt ─────────────────────────────────────────────────────
try:
    receipt = w3.eth.wait_for_transaction_receipt(tx_hash, timeout=120)
except Exception:
    print("\n  WARNING: Timeout waiting for receipt. Check BaseScan manually.")
    sys.exit(0)

print("\n" + "=" * 60)
if receipt.status == 1:
    print(f"  Status      : SUCCESS")
    print(f"  Block       : {receipt.blockNumber}")
    print(f"  Gas used    : {receipt.gasUsed}")
    print(f"  BaseScan    : https://basescan.org/tx/0x{tx_hex}")
else:
    print(f"  Status      : FAILED")
    print(f"  Gas used    : {receipt.gasUsed}")
    print(f"  Check revert reason on BaseScan:")
    print(f"  https://basescan.org/tx/0x{tx_hex}")
print("=" * 60)
